/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hillcipher;

import java.awt.Color;

public class DecryptFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DecryptFrame.class.getName());

    /**
     * Creates new form DecryptFrame
     */
    public DecryptFrame() {
        initComponents();
        customizeComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        kunci2x2Input = new javax.swing.JTextArea();
        kalimat2x2Input = new javax.swing.JTextField();
        decrypt2x2Button = new javax.swing.JButton();
        back2x2Button = new javax.swing.JButton();
        clear2x2Button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kunci3x3Input = new javax.swing.JTextArea();
        kalimat3x3Input = new javax.swing.JTextField();
        decrypt3x3Button = new javax.swing.JButton();
        back3x3Button = new javax.swing.JButton();
        clear3x3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("DECRYPT");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Kalimat/Kata yang Akan Di-Decrypt");

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("MATRIKS 2x2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Kunci Matriks");

        kunci2x2Input.setBackground(new java.awt.Color(60, 60, 60));
        kunci2x2Input.setColumns(20);
        kunci2x2Input.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        kunci2x2Input.setRows(5);
        kunci2x2Input.setText("a b\nc d");
        jScrollPane4.setViewportView(kunci2x2Input);

        kalimat2x2Input.setBackground(new java.awt.Color(60, 60, 60));
        kalimat2x2Input.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        decrypt2x2Button.setBackground(new java.awt.Color(20, 50, 100));
        decrypt2x2Button.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        decrypt2x2Button.setText("Decrypt!");
        decrypt2x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypt2x2ButtonActionPerformed(evt);
            }
        });

        back2x2Button.setBackground(new java.awt.Color(20, 50, 100));
        back2x2Button.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        back2x2Button.setText("Back To Menu");
        back2x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back2x2ButtonActionPerformed(evt);
            }
        });

        clear2x2Button.setBackground(new java.awt.Color(20, 50, 100));
        clear2x2Button.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        clear2x2Button.setText("Clear All");
        clear2x2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2x2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kalimat2x2Input, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(back2x2Button)
                                .addGap(30, 30, 30)
                                .addComponent(clear2x2Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(decrypt2x2Button)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalimat2x2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decrypt2x2Button)
                    .addComponent(back2x2Button)
                    .addComponent(clear2x2Button))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matriks 2x2", jPanel2);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Kalimat/Kata yang Akan Di-Decrypt");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("MATRIKS 3x3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Kunci Matriks");

        kunci3x3Input.setBackground(new java.awt.Color(60, 60, 60));
        kunci3x3Input.setColumns(20);
        kunci3x3Input.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        kunci3x3Input.setRows(5);
        kunci3x3Input.setText("a b c\nd e f\ng h i");
        jScrollPane2.setViewportView(kunci3x3Input);

        kalimat3x3Input.setBackground(new java.awt.Color(60, 60, 60));
        kalimat3x3Input.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        decrypt3x3Button.setBackground(new java.awt.Color(20, 50, 100));
        decrypt3x3Button.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        decrypt3x3Button.setText("Decrypt!");
        decrypt3x3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrypt3x3ButtonActionPerformed(evt);
            }
        });

        back3x3Button.setBackground(new java.awt.Color(20, 50, 100));
        back3x3Button.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        back3x3Button.setText("Back To Menu");
        back3x3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3x3ButtonActionPerformed(evt);
            }
        });

        clear3x3Button.setBackground(new java.awt.Color(20, 50, 100));
        clear3x3Button.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        clear3x3Button.setText("Clear All");
        clear3x3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear3x3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kalimat3x3Input, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back3x3Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear3x3Button)
                        .addGap(56, 56, 56)
                        .addComponent(decrypt3x3Button))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kalimat3x3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decrypt3x3Button)
                    .addComponent(back3x3Button)
                    .addComponent(clear3x3Button))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matriks 3x3", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void customizeComponents() {
        // Define colors - SAMA PERSIS DENGAN ENCRYPTFRAME
        java.awt.Color backgroundColor = new java.awt.Color(28, 28, 28);
        java.awt.Color contentPaneColor = new java.awt.Color(50, 50, 50); // LEBIH TERANG DARI BACKGROUND
        java.awt.Color buttonColor = new java.awt.Color(0, 80, 180);
        java.awt.Color inputColor = new java.awt.Color(60, 60, 60);
        java.awt.Color textColor = java.awt.Color.WHITE;

        // backgrounf
        getContentPane().setBackground(backgroundColor);

        // 2. bg untuk panel bagian content 
        jPanel2.setBackground(contentPaneColor);
        jPanel6.setBackground(contentPaneColor);
        jPanel1.setBackground(contentPaneColor);
        jPanel7.setBackground(contentPaneColor);
        jPanel3.setBackground(contentPaneColor);

        // 3. bg utk scroll panel
        jScrollPane4.getViewport().setBackground(contentPaneColor);
        jScrollPane2.getViewport().setBackground(contentPaneColor);

        // 4. bg utk tabbed pane
        jTabbedPane1.setBackground(backgroundColor);
        jTabbedPane1.setForeground(textColor);

        // 5. bg utk setiap tab content (kanan)
        jTabbedPane1.setBackgroundAt(0, contentPaneColor);
        jTabbedPane1.setBackgroundAt(1, contentPaneColor);

        // 6. custom tab component
        setupCustomTabs();

        // 7. warna label (text)
        jLabel1.setForeground(textColor);
        jLabel8.setForeground(textColor);
        jLabel9.setForeground(textColor);
        jLabel2.setForeground(textColor);
        jLabel3.setForeground(textColor);
        jLabel4.setForeground(textColor);
        jLabel10.setForeground(textColor);

        // 8. input
        kalimat2x2Input.setBackground(inputColor);
        kalimat2x2Input.setForeground(textColor);
        kunci2x2Input.setBackground(inputColor);
        kunci2x2Input.setForeground(textColor);
        kalimat3x3Input.setBackground(inputColor);
        kalimat3x3Input.setForeground(textColor);
        kunci3x3Input.setBackground(inputColor);
        kunci3x3Input.setForeground(textColor);

        // 9. button
        decrypt2x2Button.setBackground(buttonColor);
        decrypt2x2Button.setForeground(textColor);
        back2x2Button.setBackground(buttonColor);
        back2x2Button.setForeground(textColor);
        clear2x2Button.setBackground(buttonColor);
        clear2x2Button.setForeground(textColor);
        decrypt3x3Button.setBackground(buttonColor);
        decrypt3x3Button.setForeground(textColor);
        back3x3Button.setBackground(buttonColor);
        back3x3Button.setForeground(textColor);
        clear3x3Button.setBackground(buttonColor);
        clear3x3Button.setForeground(textColor);

        // 10. hapus focus border
        decrypt2x2Button.setFocusPainted(false);
        back2x2Button.setFocusPainted(false);
        clear2x2Button.setFocusPainted(false);
        decrypt3x3Button.setFocusPainted(false);
        back3x3Button.setFocusPainted(false);
        clear3x3Button.setFocusPainted(false);
    }

    private void setupCustomTabs() {
        Color backgroundColor = new Color(28, 28, 28);
        Color selectedColor = new Color(0, 80, 180); 
        Color textColor = Color.WHITE;

        for (int i = 0; i < jTabbedPane1.getTabCount(); i++) 
        {
            javax.swing.JLabel tabLabel = new javax.swing.JLabel(jTabbedPane1.getTitleAt(i));
            tabLabel.setOpaque(true);
            tabLabel.setForeground(textColor);
            tabLabel.setFont(new java.awt.Font("Bahnschrift", 1, 12));
            tabLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            tabLabel.setPreferredSize(new java.awt.Dimension(110, 40));

            if (i == jTabbedPane1.getSelectedIndex()) 
            {
                tabLabel.setBackground(selectedColor);   // warna tab aktif
            } 
            else 
            {
                tabLabel.setBackground(backgroundColor); // warna tab non-aktif
            }

            jTabbedPane1.setTabComponentAt(i, tabLabel);
        }

        // change listener yg tidak memanggil dirinya
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                updateTabSelection();
            }
        });
    }

    private void updateTabSelection() {
        Color backgroundColor = new Color(28, 28, 28);
        Color selectedColor = new Color(0, 80, 180);
        Color textColor = Color.WHITE;

        int selectedIndex = jTabbedPane1.getSelectedIndex();

        for (int i = 0; i < jTabbedPane1.getTabCount(); i++) 
        {
            java.awt.Component tabComp = jTabbedPane1.getTabComponentAt(i);
            if (tabComp instanceof javax.swing.JLabel) 
            {
                javax.swing.JLabel tabLabel = (javax.swing.JLabel) tabComp;
                if (i == selectedIndex) 
                {
                    tabLabel.setBackground(selectedColor);
                } 
                else 
                {
                    tabLabel.setBackground(backgroundColor);
                }
                tabLabel.setForeground(textColor);
            }
        }
    }
    
    private boolean validateCiphertextLength(String ciphertext, int matrixSize) {
        int ciphertextLength = ciphertext.length();

        if (ciphertextLength % matrixSize != 0) 
        {
            int neededChars = matrixSize - (ciphertextLength % matrixSize);
            int excessChars = ciphertextLength % matrixSize;

            String message = String.format(
                "Error: Ciphertext '%s' memiliki %d karakter.\n" +
                "Dengan matriks %dx%d, ciphertext harus berkelipatan %d.\n\n" +
                "Solusi:\n" +
                "• Tambahkan %d karakter (contoh: '%s%s')\n" +
                "• Atau hapus %d karakter (contoh: '%s')\n" +
                "• Atau gunakan matriks %dx%d",
                ciphertext.toUpperCase(), ciphertextLength,
                matrixSize, matrixSize, matrixSize,
                neededChars, ciphertext.toUpperCase(), "X".repeat(neededChars),
                excessChars, ciphertext.substring(0, ciphertextLength - excessChars),
                (matrixSize == 3 ? 2 : 3), (matrixSize == 3 ? 2 : 3)
            );

            javax.swing.JOptionPane.showMessageDialog(this, 
                message,
                "Error Ukuran Ciphertext", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void decrypt2x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypt2x2ButtonActionPerformed
        try {
            String ciphertext = kalimat2x2Input.getText().trim();
            String keyText = kunci2x2Input.getText().trim();

            if (ciphertext.isEmpty() || keyText.isEmpty()) 
            {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Masukkan ciphertext dan kunci matriks!", "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // validasi panjang ciphertext
            if (!validateCiphertextLength(ciphertext, 2)) {
                return;
            }

            // parse matriks kunci 2x2 dengan validasi 
            int[][] keyMatrix = HillCipherUtility.parseKeyMatrix(keyText, 2);

            // validasi kunci
            if (!HillCipherUtility.isValidKey(keyMatrix, 26)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Kunci tidak valid! Determinan harus relatif prima dengan 26.", "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // deskripsi proses
            HillCipherUtility.DecryptionResult result = HillCipherUtility.decryptWithDetails(ciphertext, keyMatrix, 0);

            // tampilkan hasil
            new HasilDecryptFrame(ciphertext, result.getPlaintext(), keyMatrix, 2, result.getSteps()).setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: " + e.getMessage(), "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_decrypt2x2ButtonActionPerformed

    private void back2x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back2x2ButtonActionPerformed
        new MenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back2x2ButtonActionPerformed

    private void clear2x2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2x2ButtonActionPerformed
        kalimat2x2Input.setText("");
        kunci2x2Input.setText("");
    }//GEN-LAST:event_clear2x2ButtonActionPerformed

    private void back3x3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3x3ButtonActionPerformed
        new MenuFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back3x3ButtonActionPerformed

    private void clear3x3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear3x3ButtonActionPerformed
        kalimat3x3Input.setText("");
        kunci3x3Input.setText("");
    }//GEN-LAST:event_clear3x3ButtonActionPerformed

    private void decrypt3x3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrypt3x3ButtonActionPerformed
        try {
            String ciphertext = kalimat3x3Input.getText().trim();
            String keyText = kunci3x3Input.getText().trim();

            if (ciphertext.isEmpty() || keyText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Masukkan ciphertext dan kunci matriks!", "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // validasi panjang ciphertext
            if (!validateCiphertextLength(ciphertext, 3)) {
                return;
            }

            // parse matriks kunci 3x3
            int[][] keyMatrix = HillCipherUtility.parseKeyMatrix(keyText, 3);

            // validasi kunci
            if (!HillCipherUtility.isValidKey(keyMatrix, 26)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Kunci tidak valid! Determinan harus relatif prima dengan 26.", "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // deskripsi proses
            HillCipherUtility.DecryptionResult result = HillCipherUtility.decryptWithDetails3x3(ciphertext, keyMatrix, 0);

            // tampilkan hasil
            new HasilDecryptFrame(ciphertext, result.getPlaintext(), keyMatrix, 3, result.getSteps()).setVisible(true);
            this.dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Terjadi error: " + e.getMessage(), "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_decrypt3x3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DecryptFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back2x2Button;
    private javax.swing.JButton back3x3Button;
    private javax.swing.JButton clear2x2Button;
    private javax.swing.JButton clear3x3Button;
    private javax.swing.JButton decrypt2x2Button;
    private javax.swing.JButton decrypt3x3Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kalimat2x2Input;
    private javax.swing.JTextField kalimat3x3Input;
    private javax.swing.JTextArea kunci2x2Input;
    private javax.swing.JTextArea kunci3x3Input;
    // End of variables declaration//GEN-END:variables
}
