/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hillcipher;

import java.util.List;

public class HasilDecryptFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HasilDecryptFrame.class.getName());
    private String ciphertext;
    private String plaintext;
    private int[][] keyMatrix;
    private int matrixSize;
    
    /**
     * Creates new form HasilDecryptFrame
     */
    public HasilDecryptFrame(String ciphertext, String plaintext, int[][] keyMatrix, int matrixSize) {
        this.ciphertext = ciphertext;
        this.plaintext = plaintext;
        this.keyMatrix = keyMatrix;
        this.matrixSize = matrixSize;
        
        initComponents();
        customizeComponents();
        displayResults();
        setLocationRelativeTo(null);
    }
   
    public HasilDecryptFrame(String ciphertext, String plaintext, int[][] keyMatrix, int matrixSize, List<String> steps) {
        this.ciphertext = ciphertext;
        this.plaintext = plaintext;
        this.keyMatrix = keyMatrix;
        this.matrixSize = matrixSize;

        initComponents();
        customizeComponents();
        displayDetailedResults(steps); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prosesDecryptionOutput = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        hasilOutput = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("HASIL DECRYPT");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses Decryption", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 14))); // NOI18N

        prosesDecryptionOutput.setEditable(false);
        prosesDecryptionOutput.setBackground(new java.awt.Color(60, 60, 60));
        prosesDecryptionOutput.setColumns(20);
        prosesDecryptionOutput.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        prosesDecryptionOutput.setRows(5);
        jScrollPane1.setViewportView(prosesDecryptionOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil Decryption", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 14))); // NOI18N

        hasilOutput.setEditable(false);
        hasilOutput.setBackground(new java.awt.Color(60, 60, 60));
        hasilOutput.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hasilOutput)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hasilOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        backButton.setBackground(new java.awt.Color(20, 50, 100));
        backButton.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(20, 20, 20)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void customizeComponents() {
        java.awt.Color backgroundColor = new java.awt.Color(28, 28, 28);
        java.awt.Color buttonColor = new java.awt.Color(0, 80, 180);
        java.awt.Color inputColor = new java.awt.Color(60, 60, 60);
        java.awt.Color textColor = java.awt.Color.WHITE;
        java.awt.Color borderColor = new java.awt.Color(20, 50, 100); // WARNA BORDER

        getContentPane().setBackground(backgroundColor);

        // bg panel
        jPanel1.setBackground(backgroundColor);
        jPanel2.setBackground(backgroundColor);

        // label (font)
        jLabel1.setForeground(textColor);

        // input 
        hasilOutput.setBackground(inputColor);
        hasilOutput.setForeground(textColor);
        prosesDecryptionOutput.setBackground(inputColor);
        prosesDecryptionOutput.setForeground(textColor);

        // button 
        backButton.setBackground(buttonColor);
        backButton.setForeground(textColor);

        // hapus focus border  dari button
        backButton.setFocusPainted(false);

        // Customize titled borders 
        try {
            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(borderColor, 3), // border luar tebal
                    javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)    // padding dalam
                ), 
                "Proses Decryption",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Bahnschrift", 1, 14),
                textColor
            ));

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(borderColor, 3), // border luar tebal
                    javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)    // padding dalam
                ),
                "Hasil Decryption",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Bahnschrift", 1, 14),
                textColor
            ));

        } catch (Exception e) {
            // fallback jika ada error
            System.out.println("Error setting border: " + e.getMessage());

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(borderColor, 3), 
                "Proses Decryption"
            ));
            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(borderColor, 3),
                "Hasil Decryption"
            ));

            // warna title dan font
            javax.swing.border.TitledBorder border1 = (javax.swing.border.TitledBorder) jPanel1.getBorder();
            border1.setTitleColor(textColor);
            border1.setTitleFont(new java.awt.Font("Bahnschrift", 1, 14));

            javax.swing.border.TitledBorder border2 = (javax.swing.border.TitledBorder) jPanel2.getBorder();
            border2.setTitleColor(textColor);
            border2.setTitleFont(new java.awt.Font("Bahnschrift", 1, 14));
        }
    }
    
    public void displayResults() {
        // tampilkan plaintext di hasil output
        hasilOutput.setText(plaintext);
        
        // tampilkan detail proses di text area
        StringBuilder processDetails = new StringBuilder();
        processDetails.append("Ciphertext: ").append(ciphertext.toUpperCase()).append("\n");
        processDetails.append("Plaintext: ").append(plaintext).append("\n\n");
        processDetails.append("Kunci Matriks ").append(matrixSize).append("x").append(matrixSize).append(":\n");
        
        // tampilkan matriks kunci
        for (int i = 0; i < matrixSize; i++) 
        {
            for (int j = 0; j < matrixSize; j++) 
            {
                processDetails.append(keyMatrix[i][j]).append(" ");
            }
            processDetails.append("\n");
        }
        
        prosesDecryptionOutput.setText(processDetails.toString());
    }
    
    public void displayDetailedResults(List<String> steps) {
        // tampilkan plaintext di hasil output
        hasilOutput.setText(plaintext);

        // tampilkan langkah-langkah detail di text area
        StringBuilder processDetails = new StringBuilder();
        for (String step : steps) {
            processDetails.append(step).append("\n");
        }

        prosesDecryptionOutput.setText(processDetails.toString());
        prosesDecryptionOutput.setCaretPosition(0); // Scroll ke atas
    }
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new DecryptFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField hasilOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea prosesDecryptionOutput;
    // End of variables declaration//GEN-END:variables
}
